/** Feature-owned state, initialized by the ordered browser bootstrap. */
export const documentPaginationState = {
  origViewToggle: undefined,
  origViewCheckbox: undefined,
  inputMode: undefined,
  docText: undefined,
  WINDOWED_MAX_CHARS: undefined,
  DOC_LINES_EMPTY: undefined,
  DOC_LINES_CONTENT: undefined,
  docLineHeight: undefined,
  DOC_LINE_VISIBILITY_THRESHOLD: undefined,
  docPagerIsPaged: undefined,
  docPages: undefined,
  activePageIndex: undefined,
  lastLookupPageIndex: undefined,
  pendingPdfLookupPageIndex: undefined,
  pageLookupTextByIndex: undefined,
  MOVEMENT_LOOKUP_IDLE_MS: undefined,
  movementLookupTimer: undefined,
  currentFile: undefined,
  currentFileType: undefined,
  pdfCacheId: undefined,
  isOriginalView: undefined,
  originalLayoutCache: undefined,
  pdfRawTextCache: undefined,
  usePdfjsTextLayer: undefined,
  pdfjsTextLayerCache: undefined,
  renderedPageImages: undefined
};
