/** Feature-owned state, initialized by the ordered browser bootstrap. */
export const settingsPanelsState = {
  displayDropdown: undefined,
  toggleDepTreeView: undefined,
  toggleGrammarOverlayAll: undefined,
  openGrammarOverlayPanel: undefined,
  grammarOverlayPanel: undefined,
  openLmWeightsPanel: undefined,
  lmWeightsPanel: undefined,
  toggleUdOverlay: undefined,
  toggleChunkHighlight: undefined,
  toggleNerOverlay: undefined,
  toggleIslandDepTree: undefined,
  toggleConnectedIslands: undefined,
  toggleConnectedIslandsAclGate: undefined,
  toggleContextWindow: undefined,
  contextWindowSizeInput: undefined,
  toggleBottomUpChunk: undefined,
  bottomUpChunkThresholdInput: undefined,
  branchDepthMinInput: undefined,
  clauseDepthDropInput: undefined,
  togglePronunciation: undefined,
  toggleGrammarPopup: undefined,
  toggleDictPopup: undefined,
  togglePdfjsTextLayer: undefined,
  pdfTextSourceGroup: undefined,
  fuzzyMaxEditDistanceInput: undefined,
  toggleComments: undefined,
  toggleSubsegmentPopups: undefined
};
